In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

We've talked about Random Forests. Now it's time to build one.

Here we'll use data from Lending Club to predict the state of a loan given some information about it. You can find the dataset [here](https://www.lendingclub.com/info/download-data.action). We'll use 2015 data. ([Thinkful mirror](https://www.dropbox.com/s/m7z42lubaiory33/LoanStats3d.csv?dl=0))

In [2]:
# Replace the path with the correct path for your data.
y2015 = pd.read_csv(
    'https://www.dropbox.com/s/0so14yudedjmm5m/LoanStats3d.csv?dl=1',
    skipinitialspace=True,
    header=1
)

# Note the warning about dtypes.

C:\Users\yfsta\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
y2015.head()

id             ...              total_il_high_credit_limit
0  68009401             ...                                 13400.0
1  68354783             ...                                 75635.0
2  68466916             ...                                 82117.0
3  68466961             ...                                 42503.0
4  68495092             ...                                 18248.0

[5 rows x 111 columns]

## The Blind Approach

Now, as we've seen before, creating a model is the easy part. Let's try just using everything we've got and throwing it without much thought into a Random Forest. SKLearn requires the independent variables to be be numeric, and all we want is dummy variables so let's use `get_dummies` from Pandas to generate a dummy variable for every categorical colummn and see what happens off of this kind of naive approach.

In [4]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
#X = pd.get_dummies(X)

#cross_val_score(rfc, X, Y, cv=5)

Did your kernel die? My kernel died.

Guess it isn't always going to be that easy...

Can you think of what went wrong?

(You're going to have to reset your kernel and reload the column, BUT DON'T RUN THE MODEL AGAIN OR YOU'LL CRASH THE KERNEL AGAIN!)

## Data Cleaning

Well, `get_dummies` can be a very memory intensive thing, particularly if data are typed poorly. We got a warning about that earlier. Mixed data types get converted to objects, and that could create huge problems. Our dataset is about 400,000 rows. If there's a bad type there its going to see 400,000 distinct values and try to create dummies for all of them. That's bad. Lets look at all our categorical variables and see how many distinct counts there are...

In [5]:
categorical = y2015.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

id
421097
term
2
int_rate
110
grade
7
sub_grade
35
emp_title
120812
emp_length
11
home_ownership
4
verification_status
3
issue_d
12
loan_status
7
pymnt_plan
1
url
421095
desc
34
purpose
14
title
27
zip_code
914
addr_state
49
earliest_cr_line
668
revol_util
1211
initial_list_status
2
last_pymnt_d
25
next_pymnt_d
4
last_credit_pull_d
26
application_type
2
verification_status_joint
3


Well that right there is what's called a problem. Some of these have over a hundred thousand distinct types. Lets drop the ones with over 30 unique values, converting to numeric where it makes sense. In doing this there's a lot of code that gets written to just see if the numeric conversion makes sense. It's a manual process that we'll abstract away and just include the conversion.

You could extract numeric features from the dates, but here we'll just drop them. There's a lot of data, it shouldn't be a huge problem.

In [6]:
# Convert ID and Interest Rate to numeric.
y2015['id'] = pd.to_numeric(y2015['id'], errors='coerce')
y2015['int_rate'] = pd.to_numeric(y2015['int_rate'].str.strip('%'), errors='coerce')

# Drop other columns with many unique variables
y2015.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'addr_state', 'desc'], 1, inplace=True)

Wonder what was causing the dtype error on the id column, which _should_ have all been integers? Let's look at the end of the file.

In [7]:
y2015.tail()

id             ...              total_il_high_credit_limit
421092  36271333.0             ...                                 33239.0
421093  36490806.0             ...                                 69919.0
421094  36271262.0             ...                                     0.0
421095         NaN             ...                                     NaN
421096         NaN             ...                                     NaN

[5 rows x 103 columns]

In [8]:
# Remove two summary rows at the end that don't actually contain data.
y2015 = y2015[:-2]

Now this should be better. Let's try again.

In [9]:
pd.get_dummies(y2015)

id                 ...                  verification_status_joint_Verified
0       68009401.0                 ...                                                   0
1       68354783.0                 ...                                                   0
2       68466916.0                 ...                                                   0
3       68466961.0                 ...                                                   0
4       68495092.0                 ...                                                   0
5       68506798.0                 ...                                                   0
6       68566886.0                 ...                                                   0
7       68577849.0                 ...                                                   0
8       66310712.0                 ...                                                   0
9       68476807.0                 ...                                                   0
10      68341763.0                 ...                                                   0
11      68356421.0                 ...                                                   0
12      68426545.0                 ...                                                   0
13      68407277.0                 ...                                                   0
14      68355089.0                 ...                                                   0
15      68466926.0                 ...                                                   0
16      68338832.0                 ...                                                   0
17      68426831.0                 ...                                                   0
18      66624733.0                 ...                                                   0
19      68616873.0                 ...                                                   0
20      67275481.0                 ...                                                   0
21      68476668.0                 ...                                                   0
22      68476702.0                 ...                                                   0
23      68436666.0                 ...                                                   0
24      68596180.0                 ...                                                   0
25      67849662.0                 ...                                                   0
26      68526883.0                 ...                                                   0
27      68607141.0                 ...                                                   0
28      68476715.0                 ...                                                   0
29      67715283.0                 ...                                                   0
...            ...                 ...                                                 ...
421065  36631385.0                 ...                                                   0
421066  36231083.0                 ...                                                   0
421067  36691397.0                 ...                                                   0
421068  36743377.0                 ...                                                   0
421069  36331554.0                 ...                                                   0
421070  36460697.0                 ...                                                   0
421071  35773415.0                 ...                                                   0
421072  36250801.0                 ...                                                   0
421073  36371802.0                 ...                                                   0
421074  36440728.0                 ...                                                   0
421075  36361815.0                 ...                                                   0
421076  35591131.0                 ...                                                   0
421077  3620

It finally works! We had to sacrifice sub grade, state address and description, but that's fine. If you want to include them you could run the dummies independently and then append them back to the dataframe.

## Second Attempt

Now let's try this model again.

We're also going to drop NA columns, rather than impute, because our data is rich enough that we can probably get away with it.

This model may take a few minutes to run.

In [10]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

array([0.97964902, 0.98076512, 0.98162   , 0.98178623, 0.96179055,
       0.9760152 , 0.96050725, 0.98064547, 0.97993208, 0.98050159])

The score cross validation reports is the accuracy of the tree. Here we're about 98% accurate.

That works pretty well, but there are a few potential problems. Firstly, we didn't really do much in the way of feature selection or model refinement. As such there are a lot of features in there that we don't really need. Some of them are actually quite impressively useless.

There's also some variance in the scores. The fact that one gave us only 93% accuracy while others gave higher than 98 is concerning. This variance could be corrected by increasing the number of estimators. That will make it take even longer to run, however, and it is already quite slow.

## DRILL: Third Attempt

So here's your task. Get rid of as much data as possible without dropping below an average of 90% accuracy in a 10-fold cross validation.

You'll want to do a few things in this process. First, dive into the data that we have and see which features are most important. This can be the raw features or the generated dummies. You may want to use PCA or correlation matrices.

Can you do it without using anything related to payment amount or outstanding principal? How do you know?


First check all of the possible loan statuses to get an idea of what loan status indicates and how often each status occurs.

In [11]:
y2015['loan_status'].value_counts()

Current               287414
Fully Paid             87989
Charged Off            29178
Late (31-120 days)      9510
In Grace Period         4320
Late (16-30 days)       1888
Default                  796
Name: loan_status, dtype: int64

For two loan statuses (Fully Paid, Charged Off), no further payments are expected while four of the loan statuses (Current, In Grace Period, Late (16-30 days) and Late (31-120) days) are related to last payment . It is unclear how to differentiate default loans but these only constitute a small portion of the data set. This suggests that payment amount and outstanding principal may not be needed as these amounts do not effect the actual loan statuses, although outstanding principal of 0 does indicate a loan that has been fully paid or charged off. Payment amount is not relevant

In [12]:
data = pd.DataFrame()
data['loan_status'] = y2015['loan_status']

For the two statuses with no further payment, the 'next_pymnt_d' is not listed (i.e. NaN).

In [13]:
data['no_next_payment'] = y2015['next_pymnt_d'].isna()==1
data['no_next_payment'] = data['no_next_payment'].astype(int)

The majority of charged off loans have non-zero amounts in 'recoveries'. For simplification, turn this into a bool and ignore magnitude.

In [14]:
data['recoveries'] = y2015['recoveries']
data['recoveries'] = data['recoveries'] > 0
data['recoveries'] = data['recoveries'].astype(int)

For the statuses based on last payment date, days since last payment needs to be calculated. Since payment dates are only listed by month and not exact date, these are only approximate but assume all dates are for the first day of the month. If the actual date is later, this will cause misclassification near each threshold, particularly those under a month. For example, some loans in the grace period may be classified as current even though they are a few days late. However, there are far more current loans than loans in the grace period so this should have a relatively minor effect.

In [15]:
last_payment_date_str = y2015['last_pymnt_d']
last_payment_date = pd.to_datetime(last_payment_date_str)

In [16]:
from datetime import datetime
data['last_payment_date'] = last_payment_date.astype('int64')//1e9
data['overdue_days'] = datetime(2017,1,1) - last_payment_date
data['overdue_days'] = data['overdue_days'].dt.total_seconds()/24/60/60

Run the model:

In [17]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

rfc = ensemble.RandomForestClassifier()
X = data[['no_next_payment','recoveries','overdue_days']]
Y = data['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

array([0.90707891, 0.90983354, 0.9101185 , 0.91539028, 0.91802422,
       0.91935407, 0.9205633 , 0.92182194, 0.92319567, 0.92564005])

The cross validation scores are all over 90% with relatively little variation using only three variables: next_pymnt_d, last_pymnt_d and recoveries.

Test using only two variables:

In [18]:
rfc = ensemble.RandomForestClassifier()
X = data[['no_next_payment','overdue_days']]
Y = data['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

array([0.89147729, 0.89147729, 0.89147729, 0.89147729, 0.89147471,
       0.89147471, 0.89149588, 0.89149588, 0.89153822, 0.89153565])

In [19]:
rfc = ensemble.RandomForestClassifier()
X = data[['no_next_payment','recoveries']]
Y = data['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

array([0.90707891, 0.90983354, 0.9101185 , 0.91539028, 0.91802422,
       0.91935407, 0.9205633 , 0.92182194, 0.92319567, 0.92564005])

In [20]:
rfc = ensemble.RandomForestClassifier()
X = data[['recoveries','overdue_days']]
Y = data['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

array([0.69813113, 0.70088575, 0.70117072, 0.7064425 , 0.70907148,
       0.71040133, 0.7116056 , 0.71286423, 0.71422804, 0.71669121])

Both models using no_next_payment and one of the other variables have accuracy around 90% while the last model only has an accuracy around 70%.

Using a single variable:

In [21]:
rfc = ensemble.RandomForestClassifier()
X = data['no_next_payment']
Y = data['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

array([0.89147729, 0.89147729, 0.89147729, 0.89147729, 0.89147471,
       0.89147471, 0.89149588, 0.89149588, 0.89153822, 0.89153565])

In [22]:
rfc = ensemble.RandomForestClassifier()
X = data['overdue_days']
Y = data['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

array([0.86362233, 0.86547458, 0.86865665, 0.87048515, 0.87202565,
       0.87387794, 0.87475362, 0.8765822 , 0.87807253, 0.87683466])

In [23]:
rfc = ensemble.RandomForestClassifier()
X = data['recoveries']
Y = data['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

array([0.69813113, 0.70088575, 0.70117072, 0.7064425 , 0.70907148,
       0.71040133, 0.7116056 , 0.71286423, 0.71422804, 0.71669121])

Using only next_pymnt_dt or last_pymnt_dt yields accuracy between 86-89% while recoveries yields an accuracy around 70%.

Applying this to the original data yields the same result:

In [24]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

rfc = ensemble.RandomForestClassifier()
X = y2015[['next_pymnt_d','recoveries']]
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

array([0.90707891, 0.90983354, 0.9101185 , 0.91539028, 0.91802422,
       0.91935407, 0.9205633 , 0.92182194, 0.92319567, 0.9256163 ])

In [25]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

rfc = ensemble.RandomForestClassifier()
X = y2015['next_pymnt_d']
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

array([0.89147729, 0.89147729, 0.89147729, 0.89147729, 0.89147471,
       0.89147471, 0.89149588, 0.89149588, 0.89153822, 0.8915119 ])

Looking back at the original loan status frequencies, this is actually not surprising because 89% of loans fall in two categories (current and fully paid off) and these can be differentiated by next payment date. Just assuming all loans with a next payment date are current (including those that are late) and loans without a next payment date are fully paid (including those that have actually been charged off) would give an accuracy of 89%. This is indicative of the unbalanced nature of the data set. However, adding a couple of more features can increase accuracy. Recoveries is important in this data set because the number of charged off loans is a significant portion (25%) of the loans with no next payment date while overdue loans are a much smaller percentage (5%) of loans with a next payment date.

In [26]:
y2015['loan_status'].value_counts()

Current               287414
Fully Paid             87989
Charged Off            29178
Late (31-120 days)      9510
In Grace Period         4320
Late (16-30 days)       1888
Default                  796
Name: loan_status, dtype: int64

In [27]:
sum(y2015['loan_status'] == 'Current') / len(y2015) + sum(y2015['loan_status'] == 'Fully Paid') / len(y2015)

0.8914924185753809